//! Experimental typed PostgreSQL document storage (RFC 296), opt-in and
//! independent of native models. Same surface as `lithair-turso`; see the
//! crate README for what differs: shared multi-process database, TLS,
//! `SERIALIZABLE` transactions with bounded retry.
use deadpool_postgres::{Manager, ManagerConfig, Pool, RecyclingMethod, Runtime};
use lithair_core::http::HttpExposable;
use serde_json::Value as Json;
use std::{
    future::Future,
    marker::PhantomData,
    path::PathBuf,
    pin::Pin,
    sync::{Arc, OnceLock},
    time::Duration,
};
use tokio::sync::OnceCell;
use tokio_postgres::{error::SqlState, IsolationLevel, Transaction};

mod command;
mod http;
mod migration;
pub use command::{Commands, Decided, Decision, View, Write};
pub use http::model_factory;
pub use migration::Migration;

pub const MAX_PAGE_SIZE: u32 = 100;
pub const MAX_BATCH_SIZE: usize = 100;
pub const MAX_DOCUMENT_BYTES: usize = 1024 * 1024;
/// Attempts for one transaction that keeps losing serialization conflicts.
pub const MAX_ATTEMPTS: u32 = 10;
/// Version of the objects this crate owns in the `lithair` schema.
const FORMAT_VERSION: i32 = 1;
/// `pg_advisory_xact_lock` key serializing format upgrades across nodes.
const FORMAT_LOCK: i64 = 0x4c49_5448_4149_5231; // "LITHAIR1"

/// Metadata generated by `DeclarativeModel` for `#[storage(postgres)]`.
/// Same contract as `lithair_turso::SqlModel`.
pub trait SqlModel: HttpExposable {
    const COLLECTION: &'static str;
    const NAMESPACE: &'static str = "default";
    const PERMISSIONS: &'static [&'static str] = &[];
    const VERSION: u32 = 1;
    const SCHEMA: &'static str = "";
    const MIGRATIONS: &'static [Migration] = &[];
    const FILTER_FIELDS: &'static [&'static str] = &[];
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid input: {0}")]
    InvalidInput(String),
    #[error("model validation: {0}")]
    Validation(String),
    #[error("schema migration: {0}")]
    Schema(String),
    #[error("permission denied")]
    Forbidden,
    #[error("record not found")]
    NotFound,
    #[error("primary key already exists")]
    Conflict,
    #[error("configuration: {0}")]
    Config(String),
    #[error("database error: {0}")]
    Database(Box<tokio_postgres::Error>),
    #[error("connection pool: {0}")]
    Pool(Box<deadpool_postgres::PoolError>),
    #[error("serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
    /// The application decision rejected the command; nothing was written.
    #[error("command rejected: {0}")]
    Command(anyhow::Error),
    #[error("write task failed: {0}")]
    Task(#[from] tokio::task::JoinError),
}
impl From<tokio_postgres::Error> for Error {
    fn from(value: tokio_postgres::Error) -> Self {
        Self::Database(Box::new(value))
    }
}
impl From<deadpool_postgres::PoolError> for Error {
    fn from(value: deadpool_postgres::PoolError) -> Self {
        Self::Pool(Box::new(value))
    }
}
impl Error {
    /// A conflict Postgres resolves by aborting one transaction: replaying it
    /// is safe because nothing it did was committed.
    fn retryable(&self) -> bool {
        matches!(self, Self::Database(e) if e.code().is_some_and(|code| {
            *code == SqlState::T_R_SERIALIZATION_FAILURE || *code == SqlState::T_R_DEADLOCK_DETECTED
        }))
    }
}
pub type Result<T> = std::result::Result<T, Error>;

/// Connection settings. The URL is a secret: `Debug` never prints it.
#[derive(Clone)]
pub struct PostgresConfig {
    url: String,
    ca_file: Option<PathBuf>,
    max_connections: usize,
    connect_timeout: Duration,
    statement_timeout: Duration,
    insecure_loopback: bool,
}

impl std::fmt::Debug for PostgresConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PostgresConfig")
            .field("url", &"[redacted]")
            .field("ca_file", &self.ca_file)
            .field("max_connections", &self.max_connections)
            .field("connect_timeout", &self.connect_timeout)
            .field("statement_timeout", &self.statement_timeout)
            .field("insecure_loopback", &self.insecure_loopback)
            .finish()
    }
}

impl PostgresConfig {
    /// A `postgres://` URL or key-value connection string. TLS is always
    /// required and verified, whatever `sslmode` says.
    pub fn new(url: impl Into<String>) -> Self {
        Self {
            url: url.into(),
            ca_file: None,
            max_connections: 16,
            connect_timeout: Duration::from_secs(5),
            statement_timeout: Duration::from_secs(30),
            insecure_loopback: false,
        }
    }
    /// Read the connection URL from an environment variable.
    pub fn from_env(variable: &str) -> Result<Self> {
        std::env::var(variable)
            .map(Self::new)
            .map_err(|_| Error::Config(format!("{variable} is not set")))
    }
    /// PEM file with the CA(s) that sign the server certificate. Without it,
    /// the operating system's trust store is used.
    pub fn with_ca_file(mut self, path: impl Into<PathBuf>) -> Self {
        self.ca_file = Some(path.into());
        self
    }
    pub fn with_max_connections(mut self, max: usize) -> Self {
        self.max_connections = max;
        self
    }
    pub fn with_connect_timeout(mut self, timeout: Duration) -> Self {
        self.connect_timeout = timeout;
        self
    }
    pub fn with_statement_timeout(mut self, timeout: Duration) -> Self {
        self.statement_timeout = timeout;
        self
    }
    /// **Tests only.** Connect without TLS to a loopback server. Never enable
    /// it in a deployment.
    pub fn allow_insecure_loopback_for_tests(mut self) -> Self {
        self.insecure_loopback = true;
        self
    }
}

/// A pool on one PostgreSQL database. Clones share the pool. Several
/// processes may connect to the same database: every transaction is
/// `SERIALIZABLE` and retried on conflict.
#[derive(Clone)]
pub struct Database {
    pool: Pool,
}

static INSTALLED: OnceLock<Database> = OnceLock::new();

impl Database {
    /// Validate the configuration, connect, and create or upgrade the objects
    /// this crate owns in the `lithair` schema. Fails closed.
    pub async fn connect(config: PostgresConfig) -> Result<Self> {
        if config.max_connections == 0 {
            return Err(Error::Config("max_connections must be positive".into()));
        }
        let mut pg: tokio_postgres::Config =
            config.url.parse().map_err(|_| Error::Config("invalid PostgreSQL URL".into()))?;
        let timeout = config.statement_timeout.as_millis();
        // Every statement, including single reads, runs SERIALIZABLE (RFC 296 Q6).
        pg.options(format!(
            "-c default_transaction_isolation=serializable -c statement_timeout={timeout}"
        ));
        pg.connect_timeout(config.connect_timeout);
        let manager_config = ManagerConfig { recycling_method: RecyclingMethod::Verified };
        let manager = if config.insecure_loopback {
            if !pg.get_hosts().iter().all(loopback) {
                return Err(Error::Config(
                    "insecure transport is limited to loopback hosts".into(),
                ));
            }
            pg.ssl_mode(tokio_postgres::config::SslMode::Disable);
            Manager::from_config(pg, tokio_postgres::NoTls, manager_config)
        } else {
            if pg
                .get_hosts()
                .iter()
                .any(|h| !matches!(h, tokio_postgres::config::Host::Tcp(_)))
            {
                return Err(Error::Config("TLS requires TCP hosts, not Unix sockets".into()));
            }
            pg.ssl_mode(tokio_postgres::config::SslMode::Require);
            Manager::from_config(pg, tls(&config)?, manager_config)
        };
        let pool = Pool::builder(manager)
            .max_size(config.max_connections)
            .wait_timeout(Some(config.connect_timeout))
            .create_timeout(Some(config.connect_timeout))
            .recycle_timeout(Some(config.connect_timeout))
            .runtime(Runtime::Tokio1)
            .build()
            .map_err(|e| Error::Config(e.to_string()))?;
        let database = Self { pool };
        database.transaction(|tx, _| Box::pin(bootstrap(tx))).await?;
        Ok(database)
    }

    /// Make this the database used by models declared `#[storage(postgres)]`.
    /// Call once, before serving.
    pub fn install(self) -> Result<()> {
        INSTALLED
            .set(self)
            .map_err(|_| Error::Config("a PostgreSQL database is already installed".into()))
    }

    pub(crate) fn installed() -> Result<Self> {
        INSTALLED.get().cloned().ok_or_else(|| {
            Error::Config("no PostgreSQL database installed; call Database::install".into())
        })
    }

    /// Namespace is selected by trusted application code, not a client permission.
    pub fn store<T: SqlModel>(&self, namespace: &str) -> Result<Store<T>> {
        if namespace.is_empty()
            || namespace.len() > 128
            || T::COLLECTION.is_empty()
            || T::COLLECTION.len() > 128
        {
            return Err(Error::InvalidInput(
                "namespace and collection must contain 1..128 bytes".into(),
            ));
        }
        if T::FILTER_FIELDS.iter().any(|field| !valid_field(field)) {
            return Err(Error::InvalidInput(
                "filter fields must be simple JSON field names".into(),
            ));
        }
        migration::validate_declaration::<T>()?;
        Ok(Store {
            database: self.clone(),
            namespace: namespace.into(),
            prepared: Arc::new(OnceCell::new()),
            marker: PhantomData,
        })
    }

    /// Run `body` in one `SERIALIZABLE` transaction, replaying it from the
    /// start on a serialization failure or deadlock (at most `MAX_ATTEMPTS`).
    /// `body` must therefore be repeatable: it may run several times, and only
    /// the last run commits.
    ///
    /// The `&'t &'a ()` argument only states that data the body borrows (`'a`)
    /// outlives each transaction (`'t`); bodies ignore it.
    pub(crate) async fn transaction<'a, R>(
        &self,
        body: impl for<'t> Fn(&'t Transaction<'t>, &'t &'a ()) -> Transacted<'t, R>,
    ) -> Result<R> {
        let mut attempt = 0;
        loop {
            attempt += 1;
            let result = async {
                let mut client = self.pool.get().await?;
                let tx = client
                    .build_transaction()
                    .isolation_level(IsolationLevel::Serializable)
                    .start()
                    .await?;
                match body(&tx, &&()).await {
                    Ok(value) => {
                        tx.commit().await?;
                        Ok(value)
                    }
                    Err(error) => {
                        // A rollback error must remain visible to the caller.
                        tx.rollback().await?;
                        Err(error)
                    }
                }
            }
            .await;
            match result {
                Err(error) if error.retryable() && attempt < MAX_ATTEMPTS => {
                    tokio::time::sleep(Duration::from_millis(2u64 << attempt.min(8))).await;
                }
                other => return other,
            }
        }
    }
}

/// The future a transaction body returns; it borrows the transaction.
pub(crate) type Transacted<'t, R> = Pin<Box<dyn Future<Output = Result<R>> + Send + 't>>;

async fn bootstrap(tx: &Transaction<'_>) -> Result<()> {
    tx.execute("SELECT pg_advisory_xact_lock($1)", &[&FORMAT_LOCK]).await?;
    tx.batch_execute(
        "CREATE SCHEMA IF NOT EXISTS lithair;
         CREATE TABLE IF NOT EXISTS lithair.format (version integer NOT NULL);",
    )
    .await?;
    let stored: Option<i32> = tx
        .query_opt("SELECT version FROM lithair.format", &[])
        .await?
        .map(|row| row.get(0));
    match stored {
        Some(version) if version > FORMAT_VERSION => {
            return Err(Error::Schema(format!(
                "the lithair schema is at format {version}; this version supports {FORMAT_VERSION}"
            )))
        }
        Some(_) => {}
        None => {
            tx.execute("INSERT INTO lithair.format (version) VALUES ($1)", &[&FORMAT_VERSION])
                .await?;
        }
    }
    // Format 1. `COLLATE "C"` keeps key order bytewise, as in Turso, so
    // pagination and keyset migration see the same order on every server.
    tx.batch_execute(
        r#"CREATE TABLE IF NOT EXISTS lithair.documents (
               namespace text COLLATE "C" NOT NULL,
               collection text COLLATE "C" NOT NULL,
               id text COLLATE "C" NOT NULL,
               body jsonb NOT NULL,
               PRIMARY KEY (namespace, collection, id));
           CREATE TABLE IF NOT EXISTS lithair.schemas (
               namespace text COLLATE "C" NOT NULL,
               collection text COLLATE "C" NOT NULL,
               version integer NOT NULL,
               schema text NOT NULL,
               PRIMARY KEY (namespace, collection));"#,
    )
    .await?;
    Ok(())
}

fn loopback(host: &tokio_postgres::config::Host) -> bool {
    match host {
        tokio_postgres::config::Host::Tcp(name) => {
            name == "localhost" || name.parse::<std::net::IpAddr>().is_ok_and(|ip| ip.is_loopback())
        }
        #[cfg(unix)]
        tokio_postgres::config::Host::Unix(_) => true,
    }
}

fn tls(config: &PostgresConfig) -> Result<tokio_postgres_rustls::MakeRustlsConnect> {
    use rustls::pki_types::{pem::PemObject, CertificateDer};
    let mut roots = rustls::RootCertStore::empty();
    match &config.ca_file {
        Some(path) => {
            for cert in CertificateDer::pem_file_iter(path)
                .map_err(|e| Error::Config(format!("CA file: {e}")))?
            {
                roots
                    .add(cert.map_err(|e| Error::Config(format!("CA file: {e}")))?)
                    .map_err(|e| Error::Config(format!("CA certificate: {e}")))?;
            }
        }
        None => {
            for cert in rustls_native_certs::load_native_certs().certs {
                let _ = roots.add(cert);
            }
        }
    }
    if roots.is_empty() {
        return Err(Error::Config("no trusted CA certificate".into()));
    }
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let tls = rustls::ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .map_err(|e| Error::Config(e.to_string()))?
        .with_root_certificates(roots)
        .with_no_client_auth();
    Ok(tokio_postgres_rustls::MakeRustlsConnect::new(tls))
}

fn valid_field(field: &str) -> bool {
    !field.is_empty() && field.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_')
}

#[derive(Clone)]
pub struct Store<T: SqlModel> {
    database: Database,
    namespace: String,
    prepared: Arc<OnceCell<()>>,
    marker: PhantomData<T>,
}

/// Atomic changes within one model and namespace. Update cannot change the ID.
#[derive(Clone)]
pub enum Mutation<T> {
    Create(T),
    Update {
        id: String,
        value: T,
    },
    Delete {
        id: String,
    },
    /// Merge top-level fields inside the transaction; revalidate the result.
    Patch {
        id: String,
        changes: Json,
    },
}

/// SQL candidate-page offset, as in `lithair-turso`.
#[derive(Debug, Clone, Copy)]
pub struct Page {
    pub limit: u32,
    pub offset: u32,
}
impl Default for Page {
    fn default() -> Self {
        Self { limit: 50, offset: 0 }
    }
}

pub(crate) struct ListedPage<T> {
    pub data: Vec<T>,
    pub next_offset: Option<u32>,
}

/// Exact string equality on an explicitly allowed top-level JSON field.
pub struct Equal<'a> {
    pub field: &'a str,
    pub value: &'a str,
}

impl<T: SqlModel> Store<T> {
    pub async fn get(&self, id: &str, permissions: &[String]) -> Result<Option<T>> {
        self.ensure_prepared().await?;
        let item = self
            .database
            .transaction(|tx, _| {
                Box::pin(async move {
                    self.check_schema(tx).await?;
                    self.load(tx, id).await
                })
            })
            .await?;
        if item.as_ref().is_some_and(|item| !item.can_read(permissions)) {
            return Err(Error::Forbidden);
        }
        Ok(item)
    }

    pub async fn list(
        &self,
        page: Page,
        filter: Option<Equal<'_>>,
        permissions: &[String],
    ) -> Result<Vec<T>> {
        Ok(self.list_page(page, filter, permissions).await?.data)
    }

    pub(crate) async fn list_page(
        &self,
        page: Page,
        filter: Option<Equal<'_>>,
        permissions: &[String],
    ) -> Result<ListedPage<T>> {
        if page.limit == 0 || page.limit > MAX_PAGE_SIZE {
            return Err(Error::InvalidInput(format!("page limit must be 1..{MAX_PAGE_SIZE}")));
        }
        let (field, value) = match &filter {
            Some(filter) => {
                if !T::FILTER_FIELDS.contains(&filter.field) {
                    return Err(Error::InvalidInput("unsupported filter field".into()));
                }
                (Some(filter.field), Some(filter.value))
            }
            None => (None, None),
        };
        self.ensure_prepared().await?;
        let rows = self
            .database
            .transaction(|tx, _| {
                Box::pin(async move {
                    self.check_schema(tx).await?;
                    // One lookahead row tells a full final page from one with more.
                    Ok(tx
                        .query(
                            "SELECT body FROM lithair.documents
                             WHERE namespace = $1 AND collection = $2
                               AND ($3::text IS NULL OR (jsonb_typeof(body -> $3) = 'string'
                                    AND body ->> $3 = $4))
                             ORDER BY id LIMIT $5 OFFSET $6",
                            &[
                                &self.namespace,
                                &T::COLLECTION,
                                &field,
                                &value,
                                &(i64::from(page.limit) + 1),
                                &i64::from(page.offset),
                            ],
                        )
                        .await?)
                })
            })
            .await?;
        let mut items = Vec::new();
        let mut next_offset = None;
        for (index, row) in rows.iter().enumerate() {
            if index as u32 == page.limit {
                next_offset = Some(page.offset.checked_add(page.limit).ok_or_else(|| {
                    Error::InvalidInput("next page offset exceeds the supported range".into())
                })?);
                break;
            }
            let item: T = serde_json::from_value(row.get::<_, Json>(0))?;
            if item.can_read(permissions) {
                items.push(item);
            }
        }
        Ok(ListedPage { data: items, next_offset })
    }

    pub async fn create(&self, value: T, permissions: &[String]) -> Result<()> {
        self.batch(vec![Mutation::Create(value)], permissions).await
    }
    pub async fn update(&self, id: &str, value: T, permissions: &[String]) -> Result<()> {
        self.batch(vec![Mutation::Update { id: id.into(), value }], permissions).await
    }
    pub async fn delete(&self, id: &str, permissions: &[String]) -> Result<()> {
        self.batch(vec![Mutation::Delete { id: id.into() }], permissions).await
    }
    /// Atomically merge a JSON object into a document. The primary key is immutable.
    pub async fn patch(&self, id: &str, changes: Json, permissions: &[String]) -> Result<()> {
        self.batch(vec![Mutation::Patch { id: id.into(), changes }], permissions).await
    }

    /// Commit all mutations or none. Once admitted, a write completes even if
    /// the caller drops this future. A timeout or lost connection during
    /// `COMMIT` is an unknown outcome: reconcile stable IDs before retrying.
    pub async fn batch(&self, mutations: Vec<Mutation<T>>, permissions: &[String]) -> Result<()> {
        if mutations.is_empty() || mutations.len() > MAX_BATCH_SIZE {
            return Err(Error::InvalidInput(format!("batch size must be 1..{MAX_BATCH_SIZE}")));
        }
        for mutation in &mutations {
            if let Mutation::Patch { changes, .. } = mutation {
                if !changes.is_object() || serde_json::to_vec(changes)?.len() > MAX_DOCUMENT_BYTES {
                    return Err(Error::InvalidInput(
                        "patch must be a JSON object within 1 MiB".into(),
                    ));
                }
            }
            if let Mutation::Create(value) | Mutation::Update { value, .. } = mutation {
                Self::encode(value, permissions)?;
            }
        }
        let store = self.clone();
        let permissions = permissions.to_vec();
        tokio::spawn(async move {
            store.ensure_prepared().await?;
            let (store, mutations, permissions) = (&store, &mutations, &permissions);
            store
                .database
                .transaction(|tx, _| {
                    Box::pin(async move {
                        store.check_schema(tx).await?;
                        for mutation in mutations {
                            store.apply(tx, mutation, permissions).await?;
                        }
                        Ok(())
                    })
                })
                .await
        })
        .await?
    }

    fn encode(value: &T, permissions: &[String]) -> Result<Json> {
        if !value.can_write(permissions) {
            return Err(Error::Forbidden);
        }
        value.validate().map_err(Error::Validation)?;
        let id = value.get_primary_key();
        if id.is_empty() || id.len() > 512 {
            return Err(Error::InvalidInput("primary key must contain 1..512 bytes".into()));
        }
        let document = serde_json::to_value(value)?;
        if !document.is_object() {
            return Err(Error::InvalidInput("model must serialize as a JSON object".into()));
        }
        if serde_json::to_vec(&document)?.len() > MAX_DOCUMENT_BYTES {
            return Err(Error::InvalidInput("document exceeds 1 MiB".into()));
        }
        Ok(document)
    }

    async fn load(&self, tx: &Transaction<'_>, id: &str) -> Result<Option<T>> {
        let row = tx
            .query_opt(
                "SELECT body FROM lithair.documents
                 WHERE namespace = $1 AND collection = $2 AND id = $3",
                &[&self.namespace, &T::COLLECTION, &id],
            )
            .await?;
        match row {
            Some(row) => Ok(Some(serde_json::from_value(row.get::<_, Json>(0))?)),
            None => Ok(None),
        }
    }

    async fn apply(
        &self,
        tx: &Transaction<'_>,
        mutation: &Mutation<T>,
        permissions: &[String],
    ) -> Result<()> {
        let (id, body) = match mutation {
            Mutation::Create(value) => {
                let id = value.get_primary_key();
                let body = Self::encode(value, permissions)?;
                let inserted = tx
                    .execute(
                        "INSERT INTO lithair.documents (namespace, collection, id, body)
                         VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING",
                        &[&self.namespace, &T::COLLECTION, &id, &body],
                    )
                    .await?;
                return if inserted == 0 { Err(Error::Conflict) } else { Ok(()) };
            }
            Mutation::Update { id, value } => {
                let previous = self.load(tx, id).await?.ok_or(Error::NotFound)?;
                if !previous.can_write(permissions) {
                    return Err(Error::Forbidden);
                }
                if *id != value.get_primary_key() {
                    return Err(Error::InvalidInput("update cannot change primary key".into()));
                }
                (id, Self::encode(value, permissions)?)
            }
            Mutation::Patch { id, changes } => {
                let previous = self.load(tx, id).await?.ok_or(Error::NotFound)?;
                if !previous.can_write(permissions) {
                    return Err(Error::Forbidden);
                }
                let mut document = serde_json::to_value(&previous)?;
                let target = document
                    .as_object_mut()
                    .ok_or_else(|| Error::InvalidInput("model must be an object".into()))?;
                let fields = changes
                    .as_object()
                    .ok_or_else(|| Error::InvalidInput("patch must be an object".into()))?;
                for (key, value) in fields {
                    if !target.contains_key(key) {
                        return Err(Error::InvalidInput(format!("unknown patch field: {key}")));
                    }
                    target.insert(key.clone(), value.clone());
                }
                let value: T = serde_json::from_value(document)
                    .map_err(|e| Error::InvalidInput(e.to_string()))?;
                if value.get_primary_key() != *id {
                    return Err(Error::InvalidInput("update cannot change primary key".into()));
                }
                (id, Self::encode(&value, permissions)?)
            }
            Mutation::Delete { id } => {
                let previous = self.load(tx, id).await?.ok_or(Error::NotFound)?;
                if !previous.can_write(permissions) {
                    return Err(Error::Forbidden);
                }
                tx.execute(
                    "DELETE FROM lithair.documents
                     WHERE namespace = $1 AND collection = $2 AND id = $3",
                    &[&self.namespace, &T::COLLECTION, id],
                )
                .await?;
                return Ok(());
            }
        };
        tx.execute(
            "UPDATE lithair.documents SET body = $4
             WHERE namespace = $1 AND collection = $2 AND id = $3",
            &[&self.namespace, &T::COLLECTION, id, &body],
        )
        .await?;
        Ok(())
    }
}
