#!/usr/bin/env bash
# Test script for 03-rest-api example
# Tests the CRUD REST API generated by DeclarativeModel
#
# Usage: ./test.sh

source "$(dirname "$0")/../../scripts/test-lib.sh"

# Clean data from previous runs
rm -rf data/todos*

start_server rest-api

API="${BASE_URL}/api/todos"

# ── CREATE ────────────────────────────────────────────────────────────────────
log_test "POST /api/todos - create a todo"
body=$(http_post "$API" '{"id":"1","title":"Learn Lithair","done":false}')
assert_status 201 "create todo"
assert_contains "$body" "Learn Lithair" "response has title"

log_test "POST /api/todos - create a second todo"
http_post "$API" '{"id":"2","title":"Build something","done":false}' >/dev/null
assert_status 201 "create second todo"

# ── UNIQUENESS ────────────────────────────────────────────────────────────────
log_test "POST with duplicate id → 409"
http_post "$API" '{"id":"1","title":"Duplicate","done":false}' >/dev/null
assert_status 409 "reject duplicate id"

# ── LIST ──────────────────────────────────────────────────────────────────────
log_test "GET /api/todos - list all"
body=$(http_get "$API")
assert_status 200 "list todos"

# ── GET BY ID ─────────────────────────────────────────────────────────────────
log_test "GET /api/todos/1"
body=$(http_get "$API/1")
assert_status 200 "get by id"
assert_contains "$body" "Learn Lithair" "correct item"

log_test "GET /api/todos/999 → 404"
http_get "$API/999" >/dev/null
assert_status 404 "not found"

# ── PATCH (partial update) ────────────────────────────────────────────────────
log_test "PATCH /api/todos/1 - mark as done"
body=$(http_patch "$API/1" '{"done":true}')
assert_status 200 "patch todo"
assert_contains "$body" '"done":true' "done is now true"

# ── IMMUTABILITY ──────────────────────────────────────────────────────────────
log_test "PUT with changed id → 400 (immutable)"
http_put "$API/1" '{"id":"changed","title":"Learn Lithair","done":true}' >/dev/null
assert_status 400 "reject immutable id change"

# ── FULL UPDATE ───────────────────────────────────────────────────────────────
log_test "PUT /api/todos/1 - full update"
body=$(http_put "$API/1" '{"id":"1","title":"Learn Lithair (done)","done":true}')
assert_status 200 "full update"
assert_contains "$body" "Learn Lithair (done)" "title updated"

# ── DELETE ────────────────────────────────────────────────────────────────────
log_test "DELETE /api/todos/1"
http_delete "$API/1" >/dev/null
assert_status 204 "delete todo"

log_test "GET deleted todo → 404"
http_get "$API/1" >/dev/null
assert_status 404 "deleted is gone"

# ── SCHEMA INTROSPECTION ─────────────────────────────────────────────────────
log_test "GET /api/todos/_schema"
body=$(http_get "$API/_schema")
assert_status 200 "schema endpoint"
assert_contains "$body" '"model"' "schema has model info"

print_summary
