//! Lithair RBAC + SSO Demo
//!
//! This example demonstrates Lithair's declarative approach to:
//! - Role-Based Access Control (RBAC)
//! - Multi-provider Single Sign-On (SSO)
//! - Field-level permissions
//! - Custom middleware
//!
//! Run with: cargo run -- --port 8080

use anyhow::Result;
use clap::Parser;
use lithair_core::app::LithairServer;
use lithair_core::rbac::{RbacUser, ServerRbacConfig};
use lithair_macros::DeclarativeModel;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// Note: This is a DEMONSTRATION of the declarative syntax.
// The actual #[derive(DeclarativeModel)], #[permission], #[idp], etc.
// macros would be implemented in lithair-macros.
// For now, we show the INTENDED syntax and simulate the behavior.

/// CLI Arguments
#[derive(Parser, Debug)]
#[command(name = "auth-rbac-mfa")]
#[command(about = "Lithair RBAC + SSO Demo", long_about = None)]
struct Args {
    /// Port to listen on
    #[arg(short, long, default_value = "8080")]
    port: u16,

    /// Host to bind to
    #[arg(long, default_value = "127.0.0.1")]
    host: String,
}

// ============================================================================
// DECLARATIVE PERMISSIONS (Simulated)
// ============================================================================

/// Product permissions
/// In the real implementation, this would be:
/// #[derive(Permission)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProductPermission {
    ProductRead,
    ProductWrite,
    ProductDelete,
    StockRead,
    StockWrite,
}

/// Admin permissions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AdminPermission {
    AdminDashboard,
    UserManagement,
}

// ============================================================================
// DECLARATIVE ROLES WITH REAL MACROS
// ============================================================================

/// User roles with associated permissions
///
/// The #[derive(RbacRole)] macro automatically generates the `has_permission` method
/// based on the #[permissions(...)] attributes on each variant.
///
/// This is TRUE declarative RBAC - no manual implementation needed!
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, lithair_macros::RbacRole)]
#[permission_type(ProductPermission)]
pub enum UserRole {
    /// Public access (no authentication required)
    #[allow(dead_code)]
    Public,

    /// Customer - can view products
    #[permissions(ProductRead)]
    Customer,

    /// Employee - can view and create products
    #[permissions(ProductRead, ProductWrite)]
    Employee,

    /// Stock Manager - can manage inventory
    #[permissions(ProductRead, StockRead, StockWrite)]
    StockManager,

    /// Product Manager - can manage products
    #[permissions(ProductRead, ProductWrite, StockRead)]
    ProductManager,

    /// Administrator - full access
    #[permissions(all)]
    Administrator,
}

// ✅ NO MANUAL IMPLEMENTATION NEEDED!
// The has_permission() method is automatically generated by the macro!

// ============================================================================
// DECLARATIVE MODEL
// ============================================================================

fn generate_uuid() -> Uuid {
    Uuid::new_v4()
}

/// Product model with field-level permissions
/// This demonstrates the DECLARATIVE RBAC syntax
///
/// In the real implementation, the #[sso] attribute would be implemented
/// For now, we show the intended syntax in comments
#[derive(Debug, Clone, Serialize, Deserialize, DeclarativeModel)]
// #[rbac(...)] is a FIELD-level attribute (see docs/reference/declarative-attributes.md).
// The struct-level form below was aspirational syntax, shown as a comment like
// #[sso] — the derive now rejects it at compile time instead of ignoring it.
// #[rbac(
//     enabled = true,
//     roles = "Customer,Employee,StockManager,ProductManager,Administrator",
//     default_role = "Customer"
// )]
// #[sso(
//     providers = "google,github,microsoft,jwt",
//     google_client_id = env("GOOGLE_CLIENT_ID"),
//     github_client_id = env("GITHUB_CLIENT_ID"),
//     microsoft_tenant_id = env("MICROSOFT_TENANT_ID")
// )]
pub struct Product {
    /// Product ID - visible to everyone
    #[db(primary_key, indexed)]
    #[lifecycle(immutable)]
    #[http(expose)]
    #[permission(read = "Public")]
    #[serde(default = "generate_uuid")]
    pub id: Uuid,

    /// Product name - public read, manager write
    #[db(indexed)]
    #[http(expose)]
    #[permission(read = "Public", write = "ProductManager")]
    pub name: String,

    /// Product description - public read, manager write
    #[http(expose)]
    #[permission(read = "Public", write = "ProductManager")]
    pub description: String,

    /// Product price - public read, manager write
    #[http(expose)]
    #[permission(read = "Public", write = "ProductManager")]
    pub price: f64,

    /// Stock quantity - restricted to stock managers
    #[http(expose)]
    #[permission(read = "StockManager", write = "StockManager")]
    pub stock: i32,

    /// Internal cost - admin only
    #[http(expose)]
    #[permission(read = "Administrator", write = "Administrator")]
    pub cost: f64,
}

impl Product {
    /// Filter fields based on user role
    pub fn filter_for_role(&self, role: &UserRole) -> serde_json::Value {
        use serde_json::json;

        let mut product = json!({
            "id": self.id,
            "name": &self.name,
            "description": &self.description,
            "price": self.price,
        });

        // Add stock if user has StockRead permission
        if role.has_permission(ProductPermission::StockRead) {
            product["stock"] = json!(self.stock);
        }

        // Add cost if user is Administrator
        if matches!(role, UserRole::Administrator) {
            product["cost"] = json!(self.cost);
        }

        product
    }
}

// ============================================================================
// MAIN
// ============================================================================

#[tokio::main]
async fn main() -> Result<()> {
    // Initialize logger
    env_logger::init();

    // Parse CLI arguments
    let args = Args::parse();

    println!("🔐 Lithair RBAC Demo");
    println!("  Users: admin/manager/stock/customer (password: password123)");
    println!("  POST /auth/login → GET /api/products");
    println!();
    println!();

    // Configure RBAC with roles and demo users
    let rbac_config = ServerRbacConfig {
        roles: vec![
            ("Administrator".to_string(), vec!["*".to_string()]),
            (
                "ProductManager".to_string(),
                vec![
                    "ProductRead".to_string(),
                    "ProductWrite".to_string(),
                    "StockRead".to_string(),
                ],
            ),
            (
                "StockManager".to_string(),
                vec!["ProductRead".to_string(), "StockRead".to_string(), "StockWrite".to_string()],
            ),
            (
                "Employee".to_string(),
                vec!["ProductRead".to_string(), "ProductWrite".to_string()],
            ),
            ("Customer".to_string(), vec!["ProductRead".to_string()]),
        ],
        users: vec![
            RbacUser::new("admin", "password123", "Administrator"),
            RbacUser::new("manager", "password123", "ProductManager"),
            RbacUser::new("stock", "password123", "StockManager"),
            RbacUser::new("customer", "password123", "Customer"),
        ],
        session_store_path: Some("./data/rbac_sessions".to_string()),
        session_duration: 3600,
    };

    // Start LithairServer with RBAC + Product CRUD
    LithairServer::new()
        .with_port(args.port)
        .with_host(&args.host)
        .with_admin_panel(true)
        .with_model::<Product>("./data/rbac_products", "/api/products")
        .with_rbac_config(rbac_config)
        .serve()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_role_permissions() {
        // Customer can only read products
        assert!(UserRole::Customer.has_permission(ProductPermission::ProductRead));
        assert!(!UserRole::Customer.has_permission(ProductPermission::ProductWrite));
        assert!(!UserRole::Customer.has_permission(ProductPermission::StockRead));

        // ProductManager can read/write products and read stock
        assert!(UserRole::ProductManager.has_permission(ProductPermission::ProductRead));
        assert!(UserRole::ProductManager.has_permission(ProductPermission::ProductWrite));
        assert!(UserRole::ProductManager.has_permission(ProductPermission::StockRead));
        assert!(!UserRole::ProductManager.has_permission(ProductPermission::StockWrite));

        // Administrator has all permissions
        assert!(UserRole::Administrator.has_permission(ProductPermission::ProductRead));
        assert!(UserRole::Administrator.has_permission(ProductPermission::ProductWrite));
        assert!(UserRole::Administrator.has_permission(ProductPermission::ProductDelete));
        assert!(UserRole::Administrator.has_permission(ProductPermission::StockRead));
        assert!(UserRole::Administrator.has_permission(ProductPermission::StockWrite));
    }

    #[test]
    fn test_field_filtering() {
        let product = Product {
            id: Uuid::new_v4(),
            name: "Test Product".to_string(),
            description: "Test description".to_string(),
            price: 99.99,
            stock: 50,
            cost: 40.0,
        };

        // Customer should not see stock or cost
        let customer_view = product.filter_for_role(&UserRole::Customer);
        assert!(customer_view.get("id").is_some());
        assert!(customer_view.get("name").is_some());
        assert!(customer_view.get("price").is_some());
        assert!(customer_view.get("stock").is_none());
        assert!(customer_view.get("cost").is_none());

        // StockManager should see stock but not cost
        let manager_view = product.filter_for_role(&UserRole::StockManager);
        assert!(manager_view.get("stock").is_some());
        assert!(manager_view.get("cost").is_none());

        // Administrator should see everything
        let admin_view = product.filter_for_role(&UserRole::Administrator);
        assert!(admin_view.get("stock").is_some());
        assert!(admin_view.get("cost").is_some());
    }
}
