//! Page-Centric development support for Lithair
//! 
//! This module provides the core traits and types for the page-centric
//! development approach, enabling declarative full-stack development.

use crate::http::Route;

/// Trait for page implementations generated by the Page derive macro
pub trait PageImplementation {
    /// Generate HTTP routes for this page
    fn routes<S>() -> Vec<Route<S>>
    where
        S: Send + Sync + 'static;
    
    /// Generate TypeScript types for external frontends
    fn typescript_types();
}

/// Configuration for page rendering modes
#[derive(Debug, Clone)]
pub enum RenderMode {
    /// Generate only APIs for external frontends (Next.js, Angular, etc.)
    ApiOnly,
    /// Generate complete HTML pages with embedded logic
    FullStack,
}

/// CORS configuration for pages
#[derive(Debug, Clone)]
pub struct CorsConfig {
    pub origins: Vec<String>,
    pub methods: Vec<String>,
    pub headers: Vec<String>,
}

impl Default for CorsConfig {
    fn default() -> Self {
        Self {
            origins: vec!["*".to_string()],
            methods: vec!["GET".to_string(), "POST".to_string(), "PUT".to_string(), "DELETE".to_string()],
            headers: vec!["Content-Type".to_string(), "Authorization".to_string()],
        }
    }
}

/// Page configuration
#[derive(Debug, Clone)]
pub struct PageConfig {
    pub render_mode: RenderMode,
    pub base_path: String,
    pub cors: CorsConfig,
    pub template: Option<String>,
}

impl Default for PageConfig {
    fn default() -> Self {
        Self {
            render_mode: RenderMode::FullStack,
            base_path: "/".to_string(),
            cors: CorsConfig::default(),
            template: None,
        }
    }
}

/// Marker type for automatic field handling
#[derive(Debug, Clone)]
pub struct Auto;

/// CRUD operations configuration
#[derive(Debug, Clone)]
pub struct CrudConfig {
    pub create: bool,
    pub read: bool,
    pub update: bool,
    pub delete: bool,
}

impl Default for CrudConfig {
    fn default() -> Self {
        Self {
            create: true,
            read: true,
            update: true,
            delete: false, // Delete is opt-in for safety
        }
    }
}

/// Permission configuration for CRUD operations
#[derive(Debug, Clone)]
pub struct PermissionConfig {
    pub create: Option<String>,
    pub read: Option<String>,
    pub update: Option<String>,
    pub delete: Option<String>,
}

impl Default for PermissionConfig {
    fn default() -> Self {
        Self {
            create: None,
            read: None,
            update: None,
            delete: None,
        }
    }
}
